INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Lenovo laptop', 99999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('HP PC', 83000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('MacBook Air M1, 8gb RAM, 3GHZ, 13inches', 99999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Huawei Phone', 23000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Alisa', 21999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Yandex IoT Device', 20999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Yandex IoT Device ', 10888);