INSERT INTO TEST.PRODUCTS (NAME, PRICE) VALUES ('Lenovo', 559888);
INSERT INTO TEST.PRODUCTS (NAME, PRICE) VALUES ('HP R', 15900);
INSERT INTO TEST.PRODUCTS (NAME, PRICE) VALUES ('MacBook Air, 16gb, 13inches', 98779);
INSERT INTO TEST.PRODUCTS (NAME, PRICE) VALUES ('Huawei P40', 1230);
INSERT INTO TEST.PRODUCTS (NAME, PRICE) VALUES ('ssd' , 15921);
INSERT INTO TEST.PRODUCTS (NAME, PRICE) VALUES ('Yandex  Device', 20939);
INSERT INTO TEST.PRODUCTS (NAME, PRICE) VALUES ('Yandex IoT Device', 10822);

INSERT INTO TEST.USERS (NAME, PASSWORD) VALUES ('ttanja', 'password');
INSERT INTO TEST.USERS (NAME, PASSWORD) VALUES ('user', 'user');
INSERT INTO TEST.USERS (NAME, PASSWORD) VALUES ('admin', '123');
